ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_code VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_expires_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS reset_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE lead_documents ADD COLUMN IF NOT EXISTS title VARCHAR(255) NOT NULL DEFAULT '';